# This template is used by setuptools-scm to generate _version.py
# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '{version}'
__scm_version__ = {scm_dict}
__commit__ = '{node}'
__distance__ = {distance}
