"""Custom version file writer for setuptools-scm"""

def write_version_file(target_path, version_dict):
    """Write a version file with commit and distance info."""
    content = f'''# coding: utf-8
# This file is automatically generated by setuptools-scm
# DO NOT EDIT

__version__ = "{version_dict['version']}"
__commit__ = "{version_dict.get('node', 'unknown')}"
__distance__ = {version_dict.get('distance', 0)}
__dirty__ = {version_dict.get('dirty', False)}
'''
    with open(target_path, 'w') as f:
        f.write(content)
